package br.net.reichel.mock.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.11
 * 2014-02-02T19:09:30.110Z
 * Generated source version: 2.6.11
 * 
 */
@WebService(targetNamespace = "http://finance.reichel.net.br/", name = "FinanceApplication")
@XmlSeeAlso({ObjectFactory.class})
public interface FinanceApplication {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "detectFraud", targetNamespace = "http://finance.reichel.net.br/", className = "br.net.reichel.mock.client.DetectFraud")
    @WebMethod
    @ResponseWrapper(localName = "detectFraudResponse", targetNamespace = "http://finance.reichel.net.br/", className = "br.net.reichel.mock.client.DetectFraudResponse")
    public br.net.reichel.mock.client.ApplicationResponse detectFraud(
        @WebParam(name = "arg0", targetNamespace = "")
        br.net.reichel.mock.client.ApplicationRequest arg0
    );
}
