package br.net.reichel.mock.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.11
 * 2014-02-02T19:09:30.118Z
 * Generated source version: 2.6.11
 * 
 */
@WebServiceClient(name = "FinanceApplicationService", 
                  wsdlLocation = "http://10.211.55.5:8080/fraud-experts/services/fraudDetection?wsdl",
                  targetNamespace = "http://finance.reichel.net.br/") 
public class FinanceApplicationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://finance.reichel.net.br/", "FinanceApplicationService");
    public final static QName FinanceApplicationPort = new QName("http://finance.reichel.net.br/", "FinanceApplicationPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.211.55.5:8080/fraud-experts/services/fraudDetection?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FinanceApplicationService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.211.55.5:8080/fraud-experts/services/fraudDetection?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FinanceApplicationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FinanceApplicationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FinanceApplicationService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FinanceApplicationService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FinanceApplicationService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FinanceApplicationService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns FinanceApplication
     */
    @WebEndpoint(name = "FinanceApplicationPort")
    public FinanceApplication getFinanceApplicationPort() {
        return super.getPort(FinanceApplicationPort, FinanceApplication.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FinanceApplication
     */
    @WebEndpoint(name = "FinanceApplicationPort")
    public FinanceApplication getFinanceApplicationPort(WebServiceFeature... features) {
        return super.getPort(FinanceApplicationPort, FinanceApplication.class, features);
    }

}
