
package br.net.reichel.mock.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.11
 * 2014-02-02T19:09:30.013Z
 * Generated source version: 2.6.11
 * 
 */
public final class FinanceApplication_FinanceApplicationPort_Client {

    private static final QName SERVICE_NAME = new QName("http://finance.reichel.net.br/", "FinanceApplicationService");

    private FinanceApplication_FinanceApplicationPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = FinanceApplicationService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        FinanceApplicationService ss = new FinanceApplicationService(wsdlURL, SERVICE_NAME);
        FinanceApplication port = ss.getFinanceApplicationPort();  
        
        {
        System.out.println("Invoking detectFraud...");
        br.net.reichel.mock.client.ApplicationRequest _detectFraud_arg0 = null;
        br.net.reichel.mock.client.ApplicationResponse _detectFraud__return = port.detectFraud(_detectFraud_arg0);
        System.out.println("detectFraud.result=" + _detectFraud__return);


        }

        System.exit(0);
    }

}
