
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package br.net.reichel.mock.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.11
 * 2014-02-02T19:09:30.095Z
 * Generated source version: 2.6.11
 * 
 */

@javax.jws.WebService(
                      serviceName = "FinanceApplicationService",
                      portName = "FinanceApplicationPort",
                      targetNamespace = "http://finance.reichel.net.br/",
                      wsdlLocation = "http://10.211.55.5:8080/fraud-experts/services/fraudDetection?wsdl",
                      endpointInterface = "br.net.reichel.mock.client.FinanceApplication")
                      
public class FinanceApplicationImpl implements FinanceApplication {

    private static final Logger LOG = Logger.getLogger(FinanceApplicationImpl.class.getName());

    /* (non-Javadoc)
     * @see br.net.reichel.mock.client.FinanceApplication#detectFraud(br.net.reichel.mock.client.ApplicationRequest  arg0 )*
     */
    public br.net.reichel.mock.client.ApplicationResponse detectFraud(br.net.reichel.mock.client.ApplicationRequest arg0) { 
        LOG.info("Executing operation detectFraud");
        System.out.println(arg0);
        try {
            br.net.reichel.mock.client.ApplicationResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
